### ISSUE TITLE
Bug: sample crashes

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [daothanhduy305/KRichEditor#12]
When I clone the repo and run the sample, I get this crash log:

```
02-21 22:51:07.486 25463-25463/com.ebolo.kricheditor E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ebolo.kricheditor, PID: 25463
    java.lang.VerifyError: Verifier rejected class org.jetbrains.anko.internals.AnkoInternals: void org.jetbrains.anko.internals.AnkoInternals.fillIntentArguments(android.content.Intent, kotlin.Pair[]) failed to verify: void org.jetbrains.anko.internals.AnkoInternals.fillIntentArguments(android.content.Intent, kotlin.Pair[]): [0xB] 'this' argument 'Reference: java.lang.Object' not instance of 'Precise Reference: kotlin.Pair' (declaration of 'org.jetbrains.anko.internals.AnkoInternals' appears in /data/app/com.ebolo.kricheditor-Y9JnDMnMID0XWzh__IC2rw==/base.apk!classes7.dex)
        at com.ebolo.kricheditor.MainActivityLayout.createView(MainActivityLayout.kt:39)
        at com.ebolo.kricheditor.MainActivityLayout.createView(MainActivityLayout.kt:8)
        at org.jetbrains.anko.AnkoContextKt.setContentView(AnkoContext.kt:135)
        at com.ebolo.kricheditor.MainActivity.onCreate(MainActivity.kt:21)
        at android.app.Activity.performCreate(Activity.java:6999)
        at android.app.Activity.performCreate(Activity.java:6990)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

**Comment by AndroidDeveloperLB** [comment]
Seems it got fixed, right?

**Comment by daothanhduy305** [comment]
I'm not sure, since I haven't been able to reproduce it on my side 🤔

**Comment by AndroidDeveloperLB** [comment]
Well I can't either.
