### ISSUE TITLE
App crashing issue - java.lang.IllegalStateException: Module with the Main dispatcher is missing

### ISSUE THREAD

**Issue by RahulSDeshpande** [daothanhduy305/KRichEditor#17]
As soon as I click on any KRichEditor toolbar icon, the app crashes with this error stack-trace!!

```
  | 0 | java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android'
  | 1 | at kotlinx.coroutines.av.a(Dispatchers.kt:1123)
  | 2 | at kotlinx.coroutines.y.a(Dispatched.kt:279)
  | 3 | at kotlinx.coroutines.b.a.a(Cancellable.kt:23)
  | 4 | at kotlinx.coroutines.r.invoke(CoroutineStart.kt:109)
  | 5 | at kotlinx.coroutines.a.a(AbstractCoroutine.kt:160)
  | 6 | at org.c.a.c.a.a$a.onClick(ListenersWithCoroutines.kt:1054)
  | 7 | at android.view.View.performClick(View.java:6259)
  | 8 | at android.view.View$PerformClick.run(View.java:24732)
  | 9 | at android.os.Handler.handleCallback(Handler.java:789)
  | 10 | at android.os.Handler.dispatchMessage(Handler.java:98)
  | 11 | at android.os.Looper.loop(Looper.java:164)
  | 12 | at android.app.ActivityThread.main(ActivityThread.java:6673)
  | 13 | at java.lang.reflect.Method.invoke(Native Method)
  | 14 | at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
  | 15 | at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
```

**Comment by RahulSDeshpande** [comment]
Hello brother, any update on this crashing issue?

**Comment by daothanhduy305** [comment]
I'm sorry for this late reply but I have just updated it to sdk 29 and androidx. I personally haven't encountered this.

**Comment by RahulSDeshpande** [comment]
The issue was related to coroutines lib version.
Later on I updated the lib version & the crash didn't occur.

Thanks & cheers 👍
